### ISSUE TITLE
please fix coolcima 

### ISSUE THREAD

**Issue by zoomq8** [aymanbest/Arabico#17]
Coolcima videos not play..please fix it

**Comment by aymanbest** [comment]
They work!!. Update your app to the pre-released version
![image](https://github.com/user-attachments/assets/855ee9ca-8413-44b4-a4ae-8fb9899452d7)
Pre-release:
![image](https://github.com/user-attachments/assets/f5eccbcd-0c81-43d8-ae2b-56ca84a2cc86)


> Coolcima videos not play..please fix it
